stages:
  - test
  - staging
  - production

test:
  image: node:latest
  stage: test
  script:
    - npm install
    - npm run test
  only:
    - master
    - staging
  tags:
    - docker

staging:
  stage: staging
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$STAGING_APP_NAME --api-key=$STAGING_API
  only:
    - staging
  tags:
    - docker

production:
  stage: production
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$APP_NAME --api-key=$HEROKU_API
  only:
    - master
  tags:
    - docker